"""Sincronizar con migracion manual de comprobantes

Revision ID: 201a92afcc49
Revises: dcdfc6fc9694
Create Date: 2025-07-02 11:05:51.710216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '201a92afcc49'
down_revision = 'dcdfc6fc9694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    op.drop_table('inventario')
    op.drop_table('predicciones')
    op.drop_table('resultados_comparativos')
    op.drop_table('usuarios')
    op.drop_table('ventas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('precio_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('fecha_venta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='ventas_producto_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='ventas_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ventas_pkey')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    sa.UniqueConstraint('email', name='usuarios_email_key'),
    sa.UniqueConstraint('username', name='usuarios_username_key')
    )
    op.create_table('resultados_comparativos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_evaluacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('periodo_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('periodo_fin', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mae', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('rmse', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('reduccion_inventario_excedente', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('incremento_ventas', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resultados_comparativos_pkey')
    )
    op.create_table('predicciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad_predicha', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('confianza', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('fecha_prediccion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modelo_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='predicciones_producto_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='predicciones_pkey')
    )
    op.create_table('inventario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_actual', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_minimo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_optimo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ubicacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ultima_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='inventario_producto_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventario_pkey')
    )
    op.create_table('productos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modelo_carro', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('precio_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('es_producto_nuevo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='productos_pkey'),
    sa.UniqueConstraint('codigo', name='productos_codigo_key')
    )
    # ### end Alembic commands ###
